---
- name: create service group
  group:
    name: "{{ nomad_group }}"
    system: true
  when: nomad_user_managed | bool

- name: create service user
  user:
    name: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    createhome: false
    system: true
    shell: /bin/false
    comment: Nomad service user
  when: nomad_user_managed | bool

- name: create conf directory
  file:
    state: directory
    path: "{{ nomad_conf_dir }}"
    owner: "{{ nomad_conf_dir_owner }}"
    group: "{{ nomad_group }}"
    mode: "{{ nomad_conf_dir_mode }}"

- name: create data directory
  file:
    state: directory
    path: "{{ nomad_data_dir }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0750

- name: write config file
  template:
    src: "{{ nomad_config_template }}"
    dest: "{{ nomad_conf_dir }}/config.json"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0640
  notify:
    - restart nomad

- name: systemd unit file
  template:
    src: "{{ nomad_systemd_template }}"
    dest: /etc/systemd/system/nomad.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart nomad

- name: manage nomad service
  service:
    name: nomad
    state: "{{ nomad_service_state }}"
    enabled: "{{ nomad_service_enabled }}"
