---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart nomad
  service:
    name: nomad
    state: restarted
  when: nomad_service_enabled | bool
    and nomad_service_restart_on_update | bool
    and nomad_service_state == 'started'
